/********************************server.js***********************
 * Express server that provides API access to a map
 *  and also acts as a proxy to the Bedrock API:
 * Exposes an endpoint /api/chat that accepts POST requests with a user message
 * and optional system prompt, forwards them to Bedrock, and returns the response.
 *
 * Requires the following environment variables:
 * - BEDROCK_API_KEY: Your Bedrock API key
 * - AWS_REGION: AWS region where Bedrock is hosted (default: eu-west-2)
 * - MODEL_ID: Bedrock model ID to use (default: eu.anthropic.claude-haiku-4-5-20251001-v1:0)
 * These are obtained from the AWS Secrets Manager
 *
 * Run this as a service: prsm-api-server.service:
 *
 * /etc/systemd/system/prsm-api-server.service
 *
 * for status, use:
 * journalctl -f -u prsm-api-server
 ****************************************************************
 *
 * or locally:
 * npm run local
 ***************************************************************/

import express from 'express'
import cors from 'cors'
import {WebsocketProvider} from 'y-websocket'
import * as Y from 'yjs'
import {createHttpTerminator} from 'http-terminator'
import {BedrockAgentRuntimeClient, RetrieveCommand} from '@aws-sdk/client-bedrock-agent-runtime'
import {ClassicLevel} from 'classic-level'
import rateLimit from 'express-rate-limit'
import {loadSecrets} from './secrets.mjs'

process.title = 'api-server'

// use local websocket server if in development mode
let websocket = 'wss://www.prsm.uk/wss'

const helpCacheLocation = process.env.HELP_CACHE_LOCATION || './helpCache'
const cacheResults = process.env.DONT_CACHE_HELP !== 'true'

if (process.env.NODE_ENV === 'dev') {
	console.log('Running in development mode')
	websocket = 'ws://localhost:1234'
}
const qualityModelId = process.env.MODEL_ID || 'eu.anthropic.claude-haiku-4-5-20251001-v1:0'
const cheapModelId = 'qwen.qwen3-235b-a22b-2507-v1:0'
const agentClient = new BedrockAgentRuntimeClient({
	region: process.env.AWS_REGION || 'eu-west-2',
})

// cache for help assistant answers, to avoid repeated calls to Bedrock for the same question
const helpCache = new ClassicLevel(helpCacheLocation, {valueEncoding: 'json'})

const app = express()
const PORT = process.env.PORT || 3001

// Rate limiting and concurrency control
const globalLimiter = rateLimit({
	windowMs: 60 * 1000, // 1 minute
	limit: 60, // 60 requests per minute per IP
	standardHeaders: true,
	legacyHeaders: false,
})

const chatLimiter = rateLimit({
	windowMs: 60 * 1000, // 1 minute
	limit: 5, // 5 chat requests per minute per IP
	standardHeaders: true,
	legacyHeaders: false,
	message: {
		error: 'Too many chat requests, please slow down and try again shortly.',
	},
})
app.set('trust proxy', 1) // trust first proxy, if behind a proxy
let inFlightChatRequests = 0
const MAX_IN_FLIGHT_CHAT = 10

// Middleware
app.use(cors({origin: ['https://prsm.uk', 'http://localhost', 'http://127.0.0.1']}))
app.use(express.json())
app.use(globalLimiter)

// Check that all incoming requests have a valid room id., and note it for use in the handlers

app.all(
	[
		'/api/chat/:room',
		'/api/map/:room',
		'/api/map/:room/allFactorsAndLinks',
		'/api/map/:room/factor/:factor',
		'/api/map/:room/link/:link',
		'/api/map/:room/styles',
		'/api/map/:room/styles/:style',
	],
	(req, res, next) => {
		try {
			checkRoom(req.params.room)
			next()
		} catch (error) {
			res.status(400).json({error: error.message})
		}
	},
)
// Proxy endpoint for Bedrock chat
app.post('/api/chat/:room', chatLimiter, async (req, res) => {
	// Bedrock configuration from environment variables
	const region = process.env.AWS_REGION || 'eu-west-2'
	const bedrockApiKey = process.env.BEDROCK_API_KEY
	logAPICalls(`Using chat for room ${req.params.room}`)

	if (!bedrockApiKey) {
		console.error('ERROR: BEDROCK_API_KEY environment variable is not set')
		return res.status(500).json({error: 'LLM API key is not set'})
	}

	if (inFlightChatRequests >= MAX_IN_FLIGHT_CHAT) {
		return res.status(503).json({error: 'Server is busy, please retry later.'})
	}

	inFlightChatRequests += 1
	try {
		const {message, systemPrompt} = req.body
		if (!message) {
			return res.status(400).json({error: 'Message is required'})
		}
		// reject excessively long prompts
		const maxPromptLength = parseInt(process.env.MAX_PROMPT_LENGTH) || 10000
		if (message.length + (systemPrompt?.length || 0) > maxPromptLength) {
			return res.status(400).json({error: `Message is too long. Please limit to ${maxPromptLength} characters.`})
		}
		const conversation = [
			{
				role: 'user',
				content: [{text: message}],
			},
		]
		const payload = {
			modelId: qualityModelId,
			messages: conversation,
			system: [
				{
					text: `${systemPrompt}  ||
\t"> ***This text has been generated by AI. It needs to be checked carefully.***". 
\tFormat your answer using Markdown. `,
				},
			],
			inferenceConfig: {maxTokens: parseInt(process.env.MAX_TOKENS) || 512, temperature: 0.5},
		}

		const url = `https://bedrock-runtime.${region}.amazonaws.com/model/${qualityModelId}/converse`
		const response = await fetch(url, {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json',
				Authorization: `Bearer ${bedrockApiKey}`,
			},
			body: JSON.stringify(payload),
		})

		if (!response.ok) {
			const errorText = await response.text()
			console.error('Bedrock API error:', errorText)
			return res.status(response.status).json({error: errorText})
		}

		const data = await response.json()
		if (data.usage) {
			logAPICalls(
				`Token usage - input: ${data.usage.inputTokens}, output: ${data.usage.outputTokens}, total: ${data.usage.totalTokens}`,
			)
		}
		const responseText = data.output.message.content[0].text

		res.json({response: responseText})
	} catch (error) {
		console.error('Server error:', error)
		res.status(500).json({error: error.message})
	} finally {
		inFlightChatRequests -= 1
	}
})

/**
 * Help Assistant Endpoint
 * Uses RAG to answer questions based on the PRSM manual
 */
app.post('/api/helpAssistant', chatLimiter, async (req, res) => {
	const {messages} = req.body
	const region = process.env.AWS_REGION || 'eu-west-2'
	const bedrockApiKey = process.env.BEDROCK_API_KEY
	const kbId = process.env.KNOWLEDGE_BASE_ID || '48IIKVEPJC'

	if (!bedrockApiKey) {
		console.error('ERROR: BEDROCK_API_KEY environment variable is not set')
		return res.status(500).json({error: 'LLM API key is not set'})
	}

	try {
		const lastUserMessage = messages[messages.length - 1].content[0].text

		// STEP -1: Check cache first
		try {
			const cachedResponse = await helpCache.get(lastUserMessage)
			if (cachedResponse) {
				logAPICalls(`Help Assistant cache hit for message: ${lastUserMessage}`)
				return res.json(cachedResponse)
			} else {
				logAPICalls(`Help Assistant cache miss for message: ${lastUserMessage}.`)
			}
		} catch (err) {
			// Cache miss or error, proceed without failing
			logAPICalls(`Help Assistant cache error for message: ${lastUserMessage}. Error: ${err.message}`)
		}

		// STEP 0: If it's a follow-up, rephrase it for the Knowledge Base search
		let standaloneQuery = lastUserMessage
		if (messages.length > 1) {
			const rephrasePayload = {
				modelId: cheapModelId, // Use Qwen here to save money,
				messages: [
					...messages.slice(0, -1),
					{
						role: 'user',
						content: [
							{
								text: `Based on the conversation above, write a specific search query to find information for the user's last request: "${lastUserMessage}". Return ONLY the search query text, no other text.`,
							},
						],
					},
				],
				inferenceConfig: {maxTokens: 50, temperature: 0},
			}

			const rephraseRes = await fetch(
				`https://bedrock-runtime.${region}.amazonaws.com/model/${cheapModelId}/converse`,
				{
					method: 'POST',
					headers: {'Content-Type': 'application/json', Authorization: `Bearer ${bedrockApiKey}`},
					body: JSON.stringify(rephrasePayload),
				},
			)
			const rephraseData = await rephraseRes.json()
			standaloneQuery = rephraseData.output.message.content[0].text
			//console.log(`Rephrased follow-up query for better retrieval: "${standaloneQuery}"`)
		}

		if (!standaloneQuery) return res.status(400).json({error: 'Message is required'})

		// STEP 1: Retrieve context from the Knowledge Base
		const retrieveCommand = new RetrieveCommand({
			knowledgeBaseId: kbId,
			retrievalQuery: {text: standaloneQuery},
			retrievalConfiguration: {
				vectorSearchConfiguration: {numberOfResults: 5},
			},
		})

		const retrieveResponse = await agentClient.send(retrieveCommand)
		const retrievalResults = retrieveResponse.retrievalResults
		const context = retrievalResults
			.map((r, index) => {
				const meta = r.content?.metadata || r.metadata || {}
				const s3Uri = r.location?.s3Location?.uri || ''
				const isManual = meta.doc_type === 'manual' || s3Uri.toLowerCase().endsWith('.md')
				const label = isManual ? 'SOURCE: PRSM USER MANUAL' : 'SOURCE: RESEARCH MATERIAL'
				return `[Source Index: ${index}] --- ${label} ---\n${r.content.text}\n`
			})
			.join('\n\n')

		// console.log(`\nChunks retrieved from KB:\n${context}`)

		// STEP 2: Generate answer using the high quality model, with the retrieved context as part of the system prompt
		const systemPrompt = `You are the PRSM Help Assistant, a technical expert for the PRSM Participatory System Mapping web application.

Your primary goal is to provide instructions based on the standard user interface and general features. You are also able to provide general guidance aboout how to conduct Participatory System Mapping.

### INTENT-BASED FILTERING (CRITICAL)
Before answering, determine the user's intent:

1. **PRACTICAL "HOW-TO" QUERIES:** (e.g., "How do I...", "Where is the button for...", "Steps to...")
   - **RULE:** You must EXCLUSIVELY use information labeled '[SOURCE: PRSM USER MANUAL]'. 
   - **ACTION:** Ignore all chunks labeled '[SOURCE: RESEARCH MATERIAL]'. Do not include definitions, theories, or academic background. Just give the steps.

2. **CONCEPTUAL/THEORETICAL QUERIES:** (e.g., "What is a link?", "Why use mapping?", "Explain the theory of...")
   - **RULE:** Use both 'MANUAL' and 'CONCEPTUAL' sources.
   - **ACTION:** Provide the theoretical definition from the research material, but follow it up by explaining how that specific concept is implemented or represented within the PRSM application using the manual.

### CONSTRAINTS
- **API EXCLUSION:** You are STRICTLY FORBIDDEN from mentioning or referencing the "PRSM API" or technical API endpoints unless the user specifically asks a question containing the word "API". 
- **SOURCE TRUTH:** Use only the provided Context. If the information is missing, state clearly that you do not know.
- **USER FOCUS:** Always prioritize providing instructions that a user can follow through the UI, even if you know there are API endpoints that could also achieve the same result. The user is not a developer and does not have access to the API.
- **PRIORITIZE MANUAL:** Always prioritize information from the PRSM manual, as this is the official source of truth for how to use the application. If other sources offer conflicting information, always default to the manual's guidance.

### RESPONSE GUIDELINES
1. **Focus:** Prioritize UI-based workflows and manual instructions.
2. For practical queries, strictly provide a numbered list of steps and nothing else.
3. **Formatting:** Always use clean Markdown with headers for organization.
4. **Examples:** Provide code snippets only when they illustrate configuration or non-API technical setups described in the manual.
5. **Clarity:** Ensure instructions are clear and actionable for users of all technical levels.
6. **Continuations:** Offer to provide more detail or cover additional topics if the user is interested.
7. **Citations:** At the very end of your response, on a final line by itself, you MUST write "USED_SOURCES: [index1, index2]" listing the numeric indices of the sources you actually extracted information from. If you ignored a source because it was the wrong doc_type, do NOT include its index.

### MANUAL CONTEXT
<context>${context}</context>`

		const finalPayload = {
			modelId: qualityModelId, // Use Haiku 4.5 for the final response
			messages,
			system: [
				{
					text: systemPrompt,
				},
			],
			inferenceConfig: {
				maxTokens: parseInt(process.env.MAX_TOKENS) || 2048,
				temperature: 0.2, // Lower temperature for factual help
			},
		}

		const url = `https://bedrock-runtime.${region}.amazonaws.com/model/${qualityModelId}/converse`
		const finalResponse = await fetch(url, {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json',
				Authorization: `Bearer ${bedrockApiKey}`,
			},
			body: JSON.stringify(finalPayload),
		})

		if (!finalResponse.ok) {
			const errorText = await finalResponse.text()
			console.error('Bedrock API error:', errorText)
			return res.status(finalResponse.status).json({error: errorText})
		}
		const finalData = await finalResponse.json()

		if (finalData.usage) {
			logAPICalls(
				`Token usage - input: ${finalData.usage.inputTokens}, output: ${finalData.usage.outputTokens}, total: ${finalData.usage.totalTokens}`,
			)
		}
		const fullAiResponse = finalData.output.message.content[0].text
		// console.log(`Full AI response:\n${fullAiResponse}\nEnd of response.`)

		// 1. Extract the indices from the "USED_SOURCES: [0, 2]" string
		const sourceMatch = fullAiResponse.match(/USED_SOURCES:\s*\[(.*?)\]/)
		const usedIndices = sourceMatch
			? sourceMatch[1]
					.split(',')
					.map((num) => parseInt(num.trim()))
					.filter((n) => !isNaN(n))
			: []

		// 2. Clean the response text for the user (remove the technical tag)
		const responseText = fullAiResponse.replace(/USED_SOURCES:\s*\[.*?\]/, '').trim()

		// 3. Map only the USED sources
		const sources = usedIndices
			.map((index) => {
				const result = retrievalResults[index]
				if (!result) return null

				const metadata = result.content?.metadata || result.metadata || {}
				return {
					name: metadata.display_name || metadata['x-amz-bedrock-kb-source-uri'] || 'Manual Source',
					url: metadata.url || result.location?.webLocation?.url || null,
				}
			})
			.filter(Boolean) // Remove any nulls
		// console.log(`Sources cited by the AI (after filtering): ${JSON.stringify(sources)}`)

		// 4. Deduplicate (in case the LLM cited two chunks from the same chapter)
		const uniqueSources = Array.from(new Map(sources.map((s) => [s.name, s])).values())

		// Cache the response for future requests. If the same question is asked again, we can return
		// the cached answer without calling Bedrock, which saves costs and reduces latency.  But do not
		// cache if it's a follow-up question, as the answer may depend on the previous conversation.
		if (cacheResults && messages.length === 1) {
			// i.e just one user message
			try {
				await helpCache.put(lastUserMessage, {
					response: responseText,
					sources: uniqueSources,
				})
				logAPICalls(`Cached response for message: ${lastUserMessage}`)
			} catch (err) {
				logAPICalls(`Failed to cache response for message: ${lastUserMessage}. Error: ${err.message}`)
			}
		}

		res.json({
			response: responseText,
			sources: uniqueSources,
		})
	} catch (error) {
		console.error('Help Assistant Error:', error)
		res.status(500).json({error: error.message})
	}
})

// Endpoints for API access to map data

// The properties of factors and links that are safe to expose through the API

const publicFactorProperties = [
	'id',
	'label',
	'x',
	'y',
	'borderWidth',
	'color',
	'created',
	'modified',
	'groupLabel',
	'grp',
	'font',
	'shape',
	'shapeProperties',
	'note',
]
const publicLinkProperties = ['id', 'from', 'to', 'label', 'created', 'modified', 'note']
/**
 * GET basic info about the map: title, background color, list of factors and links
 * Map must exist (i.e. have been created using the web interface)
 */
app.get('/api/map/:room', async (req, res) => {
	try {
		logAPICalls(`Fetching map for room ${req.params.room}`)
		const {doc, wsProvider} = await withSyncedDoc(req.params.room)
		try {
			const yNodesMap = doc.getMap('nodes')
			const yEdgesMap = doc.getMap('edges')
			const yNetMap = doc.getMap('network')
			checkMapExists(yNetMap)
			res.json({
				room: req.params.room,
				title: yNetMap.get('mapTitle'),
				viewOnly: yNetMap.get('viewOnly'),
				version: yNetMap.get('version'),
				background: yNetMap.get('background'),
				nodes: stripArray(Array.from(yNodesMap.values()), ['id', 'label', 'x', 'y']),
				edges: stripArray(Array.from(yEdgesMap.values()), ['id', 'from', 'to', 'label']),
			})
		} finally {
			doc.destroy()
			wsProvider.disconnect()
			wsProvider.destroy()
		}
	} catch (error) {
		const status = error.message === 'WebSocket sync timed out' ? 504 : 500
		res.status(status).json({error: error.message})
	}
})

/**
 * UPDATE basic map info (title and background color)
 */
app.patch('/api/map/:room', async (req, res) => {
	try {
		logAPICalls(`Updating map for room ${req.params.room}`)
		const {update} = req.body

		if (!update) {
			return res.status(400).json({error: 'Nothing provided for update'})
		}
		const {doc, wsProvider} = await withSyncedDoc(req.params.room)
		try {
			const yNetMap = doc.getMap('network')
			checkMapExists(yNetMap)
			if (update.title) {
				yNetMap.set('mapTitle', update.title)
			}
			if (update.background) {
				yNetMap.set('background', update.background)
			}
			res.json({
				room: req.params.room,
				title: yNetMap.get('mapTitle'),
				background: yNetMap.get('background'),
			})
		} catch (error) {
			res.status(500).json({error: error.message})
		} finally {
			doc.destroy()
			wsProvider.disconnect()
			wsProvider.destroy()
		}
	} catch (error) {
		const status = error.message === 'WebSocket sync timed out' ? 504 : 500
		res.status(status).json({error: error.message})
	}
})

/**
 * Return full details about all factors and links
 */
app.get('/api/map/:room/allFactorsAndLinks', async (req, res) => {
	try {
		logAPICalls(`Fetching all factors and links for room ${req.params.room}`)
		const {doc, wsProvider} = await withSyncedDoc(req.params.room)
		try {
			const yNodesMap = doc.getMap('nodes')
			console.log(`Fetched ${yNodesMap.size} factors for room ${req.params.room}`)
			const yEdgesMap = doc.getMap('edges')
			const factors = stripArray(Array.from(yNodesMap.values()), publicFactorProperties)
			const links = stripArray(Array.from(yEdgesMap.values()), publicLinkProperties)
			console.log(`Fetched ${factors.length} factors and ${links.length} links for room ${req.params.room}`)
			res.json({factors, links})
		} finally {
			doc.destroy()
			wsProvider.disconnect()
			wsProvider.destroy()
		}
	} catch (error) {
		const status = error.message === 'WebSocket sync timed out' ? 504 : 500
		res.status(status).json({error: error.message})
	}
})

/**
 * Return full details about a specific factor
 */
app.get('/api/map/:room/factor/:factor', async (req, res) => {
	try {
		logAPICalls(`Fetching factor ${req.params.factor} for room ${req.params.room}`)
		const {doc, wsProvider} = await withSyncedDoc(req.params.room)
		try {
			const yNodesMap = doc.getMap('nodes')
			const factorDetails = yNodesMap.get(req.params.factor)
			if (factorDetails) {
				res.json(strip(factorDetails, publicFactorProperties))
			} else {
				res.status(404).json({error: 'Factor not found'})
			}
		} catch (error) {
			res.status(500).json({error: error.message})
		} finally {
			doc.destroy()
			wsProvider.disconnect()
			wsProvider.destroy()
		}
	} catch (error) {
		const status = error.message === 'WebSocket sync timed out' ? 504 : 500
		res.status(status).json({error: error.message})
	}
})

/**
 * Update properties of a specific factor
 * Body must include an 'update' object with the properties to update
 */
app.patch('/api/map/:room/factor/:factor', async (req, res) => {
	try {
		logAPICalls(`Updating factor ${req.params.factor} for room ${req.params.room}`)
		const {update} = req.body

		if (!update) {
			return res.status(400).json({error: 'Nothing provided for update'})
		}

		const {doc, wsProvider} = await withSyncedDoc(req.params.room)
		try {
			const yNodesMap = doc.getMap('nodes')
			const oldFactor = yNodesMap.get(req.params.factor)
			if (oldFactor) {
				const newFactor = {...deepUpdate(oldFactor, update), modified: {time: Date.now(), user: 'API'}}
				yNodesMap.set(req.params.factor, newFactor)
				res.json(strip(newFactor, publicFactorProperties))
			} else {
				res.status(404).json({error: 'Factor not found'})
			}
		} catch (error) {
			res.status(500).json({error: error.message})
		} finally {
			doc.destroy()
			wsProvider.disconnect()
			wsProvider.destroy()
		}
	} catch (error) {
		const status = error.message === 'WebSocket sync timed out' ? 504 : 500
		res.status(status).json({error: error.message})
	}
})

/**
 * Create a new factor with specified properties
 * Body must include a 'spec' object with the factor properties
 */
app.post('/api/map/:room/factor/:factor', async (req, res) => {
	try {
		logAPICalls(`Creating factor ${req.params.factor} for room ${req.params.room}`)
		const {spec} = req.body

		// validate spec: must have at least a label
		if (!spec) {
			return res.status(400).json({error: 'Missing factor specification'})
		}
		if (!spec.label) {
			return res.status(400).json({error: 'Missing factor label in spec.'})
		}
		const newFactor = {
			// default properties, which may be overwritten by spec.
			x: 0,
			y: 0,
			borderWidth: 0,
			borderWidthSelected: 4,
			color: {
				border: 'rgb(154, 219, 180)',

				background: 'rgb(154, 219, 180)',
				highlight: {
					border: 'rgb(154, 219, 180)',
					background: 'rgb(154, 219, 180)',
				},
				hover: {
					border: 'rgb(154, 219, 180)',
					background: 'rgb(154, 219, 180)',
				},
			},
			fixed: false,
			font: {
				face: 'Oxygen',
				color: 'rgb(0, 0, 0)',
				size: 14,
			},
			groupLabel: 'Sample',
			grp: 0,
			heightConstraint: false,
			labelHighlightBold: true,
			margin: 20,
			nodeHidden: false,
			opacity: 1,
			scaling: {
				label: {enabled: false, min: 10, max: 40},
				max: 40,
				min: 10,
			},
			shape: 'box',
			shapeProperties: {borderDashes: false},
			size: 25,
			widthConstraint: false,
			...spec,
			created: {time: Date.now(), user: 'API'},
			modified: {time: Date.now(), user: 'API'},
			id: req.params.factor,
		}

		const {doc, wsProvider} = await withSyncedDoc(req.params.room)
		try {
			const yNodesMap = doc.getMap('nodes')
			yNodesMap.set(req.params.factor, newFactor)
			res.json(strip(newFactor, publicFactorProperties))
		} catch (error) {
			res.status(500).json({error: error.message})
		} finally {
			doc.destroy()
			wsProvider.disconnect()
			wsProvider.destroy()
		}
	} catch (error) {
		const status = error.message === 'WebSocket sync timed out' ? 504 : 500
		res.status(status).json({error: error.message})
	}
})

/**
 * Delete a specific factor and all links to it
 */
app.delete('/api/map/:room/factor/:factor', async (req, res) => {
	try {
		logAPICalls(`Deleting factor ${req.params.factor} for room ${req.params.room}`)
		const {doc, wsProvider} = await withSyncedDoc(req.params.room)
		try {
			const yNodesMap = doc.getMap('nodes')
			const oldFactor = yNodesMap.get(req.params.factor)
			if (oldFactor) {
				// delete all links to this factor
				for (const [edgeId, edge] of doc.getMap('edges')) {
					if (edge.from === req.params.factor || edge.to === req.params.factor) {
						doc.getMap('edges').delete(edgeId)
					}
				}
				// then delete the factor
				yNodesMap.delete(req.params.factor)
				res.json({message: 'Factor deleted'})
			} else {
				res.status(404).json({error: 'Factor not found'})
			}
		} catch (error) {
			res.status(500).json({error: error.message})
		} finally {
			doc.destroy()
			wsProvider.disconnect()
			wsProvider.destroy()
		}
	} catch (error) {
		const status = error.message === 'WebSocket sync timed out' ? 504 : 500
		res.status(status).json({error: error.message})
	}
})

/**
 * Return full details about a specific link
 */
app.get('/api/map/:room/link/:link', async (req, res) => {
	try {
		logAPICalls(`Fetching link ${req.params.link} for room ${req.params.room}`)
		const {doc, wsProvider} = await withSyncedDoc(req.params.room)
		try {
			const yEdgesMap = doc.getMap('edges')
			const linkDetails = yEdgesMap.get(req.params.link)
			if (linkDetails) {
				res.json(strip(linkDetails, publicLinkProperties))
			} else {
				res.status(404).json({error: 'Link not found'})
			}
		} catch (error) {
			res.status(500).json({error: error.message})
		} finally {
			doc.destroy()
			wsProvider.disconnect()
			wsProvider.destroy()
		}
	} catch (error) {
		const status = error.message === 'WebSocket sync timed out' ? 504 : 500
		res.status(status).json({error: error.message})
	}
})

/**
 * Update properties of a specific link
 * Body must include an 'update' object with the properties to update
 */
app.patch('/api/map/:room/link/:link', async (req, res) => {
	try {
		logAPICalls(`Updating link ${req.params.link} for room ${req.params.room}`)
		const {update} = req.body

		if (!update) {
			return res.status(400).json({error: 'Nothing provided for update'})
		}

		const {doc, wsProvider} = await withSyncedDoc(req.params.room)
		try {
			const yEdgesMap = doc.getMap('edges')
			const oldLink = yEdgesMap.get(req.params.link)
			if (oldLink) {
				const newLink = {...deepUpdate(oldLink, update), modified: {time: Date.now(), user: 'API'}}
				yEdgesMap.set(req.params.link, newLink)
				res.json(strip(newLink, publicLinkProperties))
			} else {
				res.status(404).json({error: 'Link not found'})
			}
		} catch (error) {
			res.status(500).json({error: error.message})
		} finally {
			doc.destroy()
			wsProvider.disconnect()
			wsProvider.destroy()
		}
	} catch (error) {
		const status = error.message === 'WebSocket sync timed out' ? 504 : 500
		res.status(status).json({error: error.message})
	}
})

/**
 * Create a new link with specified properties
 * Body must include a 'spec' object with the link properties
 */
app.post('/api/map/:room/link/:link', async (req, res) => {
	try {
		logAPICalls(`Creating link ${req.params.link} for room ${req.params.room}`)
		const {spec} = req.body

		// validate spec: must have at least a from and to
		if (!spec) {
			return res.status(400).json({error: 'Missing link specification'})
		}
		if (!spec.from || !spec.to) {
			return res.status(400).json({error: 'Missing link endpoints in spec.'})
		}
		const newLink = {
			// default properties, which may be overwritten by spec.
			color: {
				color: 'rgb(0,0,0)',
				highlight: 'rgb(0,0,0)',
				hover: 'rgb(0,0,0)',
			},
			font: {
				face: 'Oxygen',
				color: 'rgb(0, 0, 0)',
				size: 14,
			},
			grp: 0,
			arrows: {
				to: {
					enabled: true,
					type: 'vee',
				},
				middle: {
					enabled: false,
				},
				from: {
					enabled: false,
				},
			},
			dashes: false,
			edgeHidden: false,
			groupLabel: 'Sample',
			hoverWidth: 1,
			labelHighlightBold: false,
			selectionWidth: 0,
			width: 1,
			...spec,
			created: {time: Date.now(), user: 'API'},
			modified: {time: Date.now(), user: 'API'},
			id: req.params.link,
		}

		const {doc, wsProvider} = await withSyncedDoc(req.params.room)
		try {
			const yNodesMap = doc.getMap('nodes')
			const edgesMap = doc.getMap('edges')
			// also ensure that the nodes exist
			if (!yNodesMap.has(newLink.from) || !yNodesMap.has(newLink.to)) {
				res.status(400).json({error: 'One or both link endpoints do not exist as factors.'})
			} else {
				edgesMap.set(req.params.link, newLink)
				res.json(strip(newLink, publicLinkProperties))
			}
		} catch (error) {
			res.status(500).json({error: error.message})
		} finally {
			doc.destroy()
			wsProvider.disconnect()
			wsProvider.destroy()
		}
	} catch (error) {
		const status = error.message === 'WebSocket sync timed out' ? 504 : 500
		res.status(status).json({error: error.message})
	}
})

/**
 * Delete a specific link
 */
app.delete('/api/map/:room/link/:link', async (req, res) => {
	try {
		logAPICalls(`Deleting link ${req.params.link} for room ${req.params.room}`)

		const {doc, wsProvider} = await withSyncedDoc(req.params.room)
		try {
			const yEdgesMap = doc.getMap('edges')
			const oldLink = yEdgesMap.get(req.params.link)
			if (oldLink) {
				yEdgesMap.delete(req.params.link)
				res.json({message: 'Link deleted'})
			} else {
				res.status(404).json({error: 'Link not found'})
			}
		} catch (error) {
			res.status(500).json({error: error.message})
		} finally {
			doc.destroy()
			wsProvider.disconnect()
			wsProvider.destroy()
		}
	} catch (error) {
		const status = error.message === 'WebSocket sync timed out' ? 504 : 500
		res.status(status).json({error: error.message})
	}
})
/**
 *  Return a list of all styles (colors, fonts, shapes) used in the map, for factors and links.
 */
app.get('/api/map/:room/styles', async (req, res) => {
	try {
		logAPICalls(`Fetching styles for room ${req.params.room}`)
		const {doc, wsProvider} = await withSyncedDoc(req.params.room)
		try {
			const ySamplesMap = doc.getMap('samples')
			const styles = Array.from(ySamplesMap.entries()).filter((style) => /^(edge|group)/.test(style[0]))
			res.json(styles)
		} catch (error) {
			res.status(500).json({error: error.message})
		} finally {
			doc.destroy()
			wsProvider.disconnect()
			wsProvider.destroy()
		}
	} catch (error) {
		const status = error.message === 'WebSocket sync timed out' ? 504 : 500
		res.status(status).json({error: error.message})
	}
})

/**
 *  Return the info for the given style.
 */
app.get('/api/map/:room/styles/:style', async (req, res) => {
	try {
		logAPICalls(`Fetching styles for room ${req.params.room}`)
		const {doc, wsProvider} = await withSyncedDoc(req.params.room)
		try {
			const ySamplesMap = doc.getMap('samples')
			const style = ySamplesMap.get(req.params.style)
			if (style) {
				res.json([req.params.style, style])
			} else {
				res.status(404).json({error: 'Style not found'})
			}
		} catch (error) {
			res.status(500).json({error: error.message})
		} finally {
			doc.destroy()
			wsProvider.disconnect()
			wsProvider.destroy()
		}
	} catch (error) {
		const status = error.message === 'WebSocket sync timed out' ? 504 : 500
		res.status(status).json({error: error.message})
	}
})

app.patch('/api/map/:room/styles/:style', async (req, res) => {
	try {
		logAPICalls(`Updating style ${req.params.style} for room ${req.params.room}`)
		const {update} = req.body

		if (!update) {
			return res.status(400).json({error: 'Nothing provided for update'})
		}

		const {doc, wsProvider} = await withSyncedDoc(req.params.room)
		try {
			const yStylesMap = doc.getMap('samples')
			const oldStyle = yStylesMap.get(req.params.style)
			if (oldStyle) {
				const newStyle = deepUpdate(oldStyle, update)
				yStylesMap.set(req.params.style, newStyle)
				res.json(newStyle)
			} else {
				res.status(404).json({error: 'Style not found'})
			}
		} catch (error) {
			res.status(500).json({error: error.message})
		} finally {
			doc.destroy()
			wsProvider.disconnect()
			wsProvider.destroy()
		}
	} catch (error) {
		const status = error.message === 'WebSocket sync timed out' ? 504 : 500
		res.status(status).json({error: error.message})
	}
})

let server // server instance
let httpTerminator // terminator instance
/**
 * Start the server after loading secrets
 */
async function start() {
	// Load secrets first
	await loadSecrets()
	// Start the server
	server = app.listen(PORT, () => {
		console.log(
			`Proxy server running on http://localhost:${PORT} using websocket server at ${websocket}, 
			models ${qualityModelId} and ${cheapModelId} and 
			helpCache at ${helpCache.location}`,
		)
	})
	httpTerminator = createHttpTerminator({server})
}
start()

/****** Utilities  ************/

const WS_TIMEOUT_MS = 10000
/**
 * Return a promise that resolves with the Y.Doc and WebsocketProvider for a given room once the document is synced
 * Rejects if syncing takes longer than WS_TIMEOUT_MS
 * @param {string} room
 * @returns Promise that resolves with {doc, wsProvider}
 */
function withSyncedDoc(room) {
	return new Promise((resolve, reject) => {
		const doc = new Y.Doc()
		const wsProvider = new WebsocketProvider(websocket, `prsm${room}`, doc)
		const timer = setTimeout(() => {
			doc.destroy()
			wsProvider.disconnect()
			wsProvider.destroy()
			reject(new Error('WebSocket sync timed out'))
		}, WS_TIMEOUT_MS)
		wsProvider.on('synced', () => {
			clearTimeout(timer)
			resolve({doc, wsProvider})
		})
	})
}

// Graceful shutdown on Ctrl-C and systemctl stop
process.on('SIGINT', () => {
	console.log('\nReceived SIGINT, shutting down...')
	handleShutdown()
})
process.on('SIGTERM', () => {
	console.log('\nReceived SIGTERM, shutting down...')
	handleShutdown()
})
async function handleShutdown() {
	await httpTerminator.terminate()
	await helpCache.close()
	console.log('Help cache closed')
	console.log('HTTP server closed')
	process.exit(0)
}

/**
 * Check that a room identifier is properly formed
 * @param {string} room
 * @throws {Error} if room is invalid
 */
function checkRoom(room) {
	if (!room || !room.match(/^[A-Z]{3}-[A-Z]{3}-[A-Z]{3}-[A-Z]{3}$/)) {
		throw new Error(`Invalid room identifier: ${room}`)
	}
}
/**
 * Check that a map has been created using the web interface
 * Since there is no way to list existing Yjs documents on the server,
 * we check for the presence of the 'lastLoaded' property in the network map
 * @param {Y.Map} yNetMap
 */
function checkMapExists(yNetMap) {
	const lastLoaded = yNetMap.get('lastLoaded')
	if (!lastLoaded) {
		throw new Error('Map not found.  Have you created the map through the PRSM web interface?')
	}
}
/**
 * time stamp and output message to console
 * @param {string} message
 */
function logAPICalls(message) {
	const timestamp = new Date().toLocaleString()
	console.log(`[${timestamp}] ${message}`)
}

// utility functions
/**
 * Recursively updates properties in a target object with values from an update object.
 * Searches deeply through nested objects to find and update matching keys.
 * Only updates keys that already exist in the target object; it does not add new keys.
 * Stops as soon as a match is found and updated, so if there are multiple nested objects
 * with the same key, only the first one encountered will be updated.
 *
 * @param {Object} target - The object to update
 * @param {Object} updates - Object containing key-value pairs to update
 * @returns {Object} The updated target object
 */
function deepUpdate(target, updates) {
	const result = structuredClone(target)
	for (const [key, value] of Object.entries(updates)) {
		if (Object.hasOwn(result, key)) {
			result[key] = value
		} else {
			for (const prop in result) {
				if (typeof result[prop] === 'object' && result[prop] !== null) {
					if (Object.hasOwn(result[prop], key)) {
						result[prop][key] = value
						break
					}
					result[prop] = deepUpdate(result[prop], {[key]: value})
				}
			}
		}
	}
	return result
}
/**
 * return a copy of an object that only includes the properties that are in allowed
 * @param {Object} obj the object to copy
 * @param {array} allowed list of allowed properties
 */
function strip(obj, allowed) {
	return allowed.reduce((a, e) => {
		a[e] = obj[e]
		return a
	}, {})
}
/**
 * return an array of objects, each stripped to only include the allowed properties
 * @param {array} arr
 * @param {array} allowed
 * @returns
 */
function stripArray(arr, allowed) {
	return arr.map((item) => strip(item, allowed))
}
