/*
 * Invoke AWS Bedrock LLM model using AWS SDK for JavaScript v3
 *
 * Communicates with a proxy server that accesses Bedrock API
 * 
 * Example: Explain the causal link between consumer energy bills and greenhouse gas emissions
 */

// Backend API endpoint
const API_ENDPOINT = 'http://localhost:4001/api/chat'
//const API_ENDPOINT = 'https://cress.soc.surrey.ac.uk/api/chat'

// ================================================================================

import { marked } from "marked"

export async function chat(userMessage) {
	try {
		// set the system prompt
		const systemPrompt = [{
			text: `
		Answer concisely in no more than 200 words.
		The user will ask you to 'Explain the causal link between XXX and YYY'. Provide evidence, such as links to relevant web page, to justify your statements.
		Structure the answer in these sections: introduction, bullet points, evidence, summary.
		Do not include a title or section headings. Start the answer with: 
		"#### _This text has been generated by AI._". 
		Format your answer using Markdown. `
		}]

		// Call backend proxy API
		const response = await fetch(API_ENDPOINT, {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json',
			},
			body: JSON.stringify({
				message: userMessage,
				systemPrompt: systemPrompt,
				room: 'FAK-ERO-OMK-EYX'
			})
		})
		
		if (!response.ok) {
			const errorData = await response.json()
			throw new Error(`HTTP ${response.status}: ${errorData.error || 'Unknown error'}`)
		}
		
		const data = await response.json()

		// Extract and print the response text
		const responseText = data.response
		console.log(responseText)
		// Convert Markdown to HTML
		return marked.parse(responseText, {breaks: true})
	} catch (err) {
		console.log(`ERROR: ${err.message}`)
		return `<p style="color: red;">Error: ${err.message}</p>`
	}
}
	

async function submitText() {
	const input = document.getElementById('inputText').value
	const output = document.getElementById('outputText')
	output.innerHTML = input ? await chat(input) : 'Please enter some text.'
}
window.submitText = submitText

